Repository Semoban/meongcare-AOS, pull requests merged in 2023-12, with the labels that each got.

#35 design: 알림 화면 및 캘린더 디자인 수정
  app/src/main/assets/pretendard_regular.otf
  app/src/main/java/com/project/meongcare/CalendarBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/HomeFragment.kt
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/res/drawable/all_calendar_bottom_sheet.xml
  app/src/main/res/drawable/notice_toggle_checked.xml
  app/src/main/res/drawable/notice_toggle_unchecked.xml
  app/src/main/res/drawable/pet_food_search.xml
  app/src/main/res/layout/fragment_calendar_bottom_sheet.xml
  app/src/main/res/layout/fragment_inform.xml
  app/src/main/res/layout/fragment_notice_delete.xml
  app/src/main/res/layout/fragment_supplement.xml
  app/src/main/res/layout/fragment_supplement_add.xml
  app/src/main/res/layout/fragment_supplement_info.xml
  app/src/main/res/layout/fragment_supplement_routine_edit.xml
  app/src/main/res/layout/fragment_supplement_search.xml
  app/src/main/res/layout/fragment_symptom.xml
  app/src/main/res/layout/fragment_symptom_add.xml
  app/src/main/res/layout/fragment_symptom_info.xml
  app/src/main/res/layout/fragment_symptom_list_edit.xml
  app/src/main/res/layout/fragment_symptom_select.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/layout/item_supplement_routine_edit.xml
  app/src/main/res/menu/menu_info.xml
  app/src/main/res/values/strings-calendar.xml
  app/src/main/res/values/styles.xml
Labels: feat, design

#37 feat: 체중 주간, 월간 그래프 구현
  app/src/main/assets/pretendard_medium.otf
  app/src/main/java/com/project/meongcare/WeightFragment.kt
  app/src/main/java/com/project/meongcare/weight/WeightCustomMarker.kt
  app/src/main/java/com/project/meongcare/weight/WeightFragment.kt
  app/src/main/res/drawable/weight_rec_main4_r2.xml
  app/src/main/res/drawable/weight_weekly_chart_gradient.xml
  app/src/main/res/layout/fragment_weight.xml
  app/src/main/res/layout/layout_weight_edit_dialog.xml
  app/src/main/res/layout/weight_marker.xml
Labels: feat, design

#38 design: 상태 바 속성, 글자 속성 추가
  app/src/main/res/values/themes.xml
  app/src/main/res/values/typography.xml
Labels: design

#41 fix: 파일 이름 변경으로 오류 발생하는 background 속성 수정
  app/src/main/res/layout/fragment_feed_add_edit.xml
  app/src/main/res/layout/fragment_feed_info.xml
  app/src/main/res/layout/layout_weight_edit_dialog.xml
Labels: bug

#44 fix: Main Activity에서 프래그먼트 교체하는 함수 삭제
  app/src/main/java/com/project/meongcare/CalendarDontKnowVersionBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/HomeFragment.kt
  app/src/main/java/com/project/meongcare/InformFragment.kt
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/NoticeDeleteFragment.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogAddOnBoardingFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/OnBoardingFragment.kt
  app/src/main/res/color/color_text_button.xml
  app/src/main/res/drawable/all_radio_btn_selected.xml
  app/src/main/res/drawable/all_radio_btn_unselected.xml
  app/src/main/res/drawable/calendar_radio_button_selector.xml
  app/src/main/res/layout/fragment_calendar_dont_know_version_bottom_sheet.xml
  app/src/main/res/layout/fragment_dog_add_on_boarding.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_symptom_add.xml
  app/src/main/res/layout/fragment_symptom_select.xml
  app/src/main/res/layout/fragment_symptom_select_custom.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/typography.xml
Labels: bug, feat, design

#46 fix: tempActivity -> mainActivity 변경으로 참조 오류 해결
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/symptom/model/data/repository/SymptomRepository.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomFragment.kt
Labels: bug

#51 design: 스플래쉬 화면 로고 삽입
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/meongcare_logo_login.xml
  app/src/main/res/drawable/meongcare_logo_splash.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
Labels: design

#53 design: 홈 화면 강아지 프로필 배경 수정
  app/src/main/res/drawable/home_dog_image_bg.png
  app/src/main/res/drawable/home_dog_profile_bg_select.xml
  app/src/main/res/drawable/home_dog_profile_bg_unselect.xml
  app/src/main/res/layout/item_home_dog_profile.xml
Labels: design

#54 feat: 강아지 등록 화면 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/meongcare/CalendarBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/CalendarDontKnowVersionBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/PhotoSelectBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/local/DateSubmitListener.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/local/PhotoMenuListener.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/remote/DogAddApi.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/remote/DogAddRetrofitClient.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/repository/DogAddModule.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/repository/DogAddRepository.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/repository/DogAddRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/onboarding/model/entities/Dog.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogAddOnBoardingFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogVarietySearchFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/viewmodel/DogAddViewModel.kt
  app/src/main/res/drawable/all_rect_r5.xml
  app/src/main/res/drawable/dog_add_error_rect_r5.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_calendar_bottom_sheet.xml
  app/src/main/res/layout/fragment_calendar_dont_know_version_bottom_sheet.xml
  app/src/main/res/layout/fragment_dog_add_on_boarding.xml
  app/src/main/res/layout/fragment_dog_variety_search.xml
  app/src/main/res/layout/fragment_photo_select_bottom_sheet.xml
  app/src/main/res/xml/file_paths.xml
Labels: feat, design

#57 feat: Access Token 재발급 API 연결
  app/src/main/java/com/project/meongcare/login/model/data/remote/LoginApi.kt
  app/src/main/java/com/project/meongcare/login/model/data/repository/LoginRepository.kt
  app/src/main/java/com/project/meongcare/login/model/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/login/model/entities/LoginResponse.kt
Labels: feat

#59 feat: 네비게이션 초기 셋팅
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat, design

#61 feat: bottomsheet 프로세스 변경 및 기능 추가
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomAddFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomUtils.kt
  app/src/main/java/com/project/meongcare/toolbar/view/CalendarBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/toolbar/view/ToolbarFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/themes.xml
Labels: feat, design

#62 feat: 체중 POST, PATCH, GET(일, 주, 월) 기능 구현
  app/build.gradle
  app/src/main/java/com/project/meongcare/weight/model/data/remote/WeightClient.kt
  app/src/main/java/com/project/meongcare/weight/model/data/remote/WeightRemoteDataSource.kt
  app/src/main/java/com/project/meongcare/weight/model/data/remote/WeightService.kt
  app/src/main/java/com/project/meongcare/weight/model/data/repository/WeightModule.kt
  app/src/main/java/com/project/meongcare/weight/model/data/repository/WeightRepository.kt
  app/src/main/java/com/project/meongcare/weight/model/data/repository/WeightRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/weight/model/entities/WeightDayResponse.kt
  app/src/main/java/com/project/meongcare/weight/model/entities/WeightGetRequest.kt
  app/src/main/java/com/project/meongcare/weight/model/entities/WeightMonthResponse.kt
  app/src/main/java/com/project/meongcare/weight/model/entities/WeightPatchRequest.kt
  app/src/main/java/com/project/meongcare/weight/model/entities/WeightPostRequest.kt
  app/src/main/java/com/project/meongcare/weight/model/entities/WeightWeekResponse.kt
  app/src/main/java/com/project/meongcare/weight/model/entities/WeightWeeksResponse.kt
  app/src/main/java/com/project/meongcare/weight/view/WeightCustomMarker.kt
  app/src/main/java/com/project/meongcare/weight/view/WeightFragment.kt
  app/src/main/java/com/project/meongcare/weight/viewmodel/WeightViewModel.kt
  app/src/main/res/layout/fragment_weight.xml
  app/src/main/res/layout/layout_weight_edit_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#64 feat: 홈 화면 기능 구현
  app/src/main/java/com/project/meongcare/HomeFragment.kt
  app/src/main/java/com/project/meongcare/home/model/data/remote/HomeApi.kt
  app/src/main/java/com/project/meongcare/home/model/data/remote/HomeRetrofitClient.kt
  app/src/main/java/com/project/meongcare/home/model/data/repository/HomeModule.kt
  app/src/main/java/com/project/meongcare/home/model/data/repository/HomeRepository.kt
  app/src/main/java/com/project/meongcare/home/model/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/home/model/entities/HomeGetDogListResponse.kt
  app/src/main/java/com/project/meongcare/home/model/entities/HomeGetExcretaResponse.kt
  app/src/main/java/com/project/meongcare/home/model/entities/HomeGetFeedResponse.kt
  app/src/main/java/com/project/meongcare/home/model/entities/HomeGetProfileResponse.kt
  app/src/main/java/com/project/meongcare/home/model/entities/HomeGetSupplementsResponse.kt
  app/src/main/java/com/project/meongcare/home/model/entities/HomeGetSymptomResponse.kt
  app/src/main/java/com/project/meongcare/home/model/entities/HomeGetWeightResponse.kt
  app/src/main/java/com/project/meongcare/home/view/DogProfileClickListener.kt
  app/src/main/java/com/project/meongcare/home/view/HomeDogProfileAdapter.kt
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/java/com/project/meongcare/home/view/HomeHorizonCalendarAdapter.kt
  app/src/main/java/com/project/meongcare/home/view/HomeSymptomAdapter.kt
  app/src/main/java/com/project/meongcare/home/view/HorizonCalendarItemClickListener.kt
  app/src/main/java/com/project/meongcare/home/viewmodel/HomeViewModel.kt
  app/src/main/res/drawable/home_dog_default.xml
  app/src/main/res/drawable/home_dog_profile_bg_select.xml
  app/src/main/res/drawable/symptom_etc_record.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_dog_profile.xml
  app/src/main/res/layout/item_home_symptom.xml
  app/src/main/res/values/strings-home.xml
Labels: feat, design

#68 feat: 이상증상 리스트 편집 기능, 데이터 없을 시 이벤트 추가
  app/src/main/java/com/project/meongcare/symptom/model/data/remote/SymptomAPI.kt
  app/src/main/java/com/project/meongcare/symptom/model/data/repository/SymptomRepository.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomAddFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomInfoFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomUtils.kt
  app/src/main/java/com/project/meongcare/symptom/viewmodel/SymptomViewModel.kt
  app/src/main/res/drawable/all_paws.xml
  app/src/main/res/layout/bottomsheet_symptom_add_date.xml
  app/src/main/res/layout/fragment_symptom.xml
  app/src/main/res/layout/fragment_symptom_add.xml
  app/src/main/res/layout/fragment_symptom_edit.xml
  app/src/main/res/layout/fragment_symptom_list_edit.xml
  app/src/main/res/layout/item_symptom_list_edit.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat, design

#71 feat: 메인 액티비티에 바텀 내비게이션의 표시 여부를 한 번에 관리하는 로직 추가
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#72 로그인, 온보딩, 메인, 알림 화면 nav graph에 추가
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/OnBoardingFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomAddFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomInfoFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: design

#76 feat: 알림 api 연결
  app/src/main/java/com/project/meongcare/NoticeTabEventFragment.kt
  app/src/main/java/com/project/meongcare/NoticeTabNoticeFragment.kt
  app/src/main/java/com/project/meongcare/notice/model/data/remote/NoticeApi.kt
  app/src/main/java/com/project/meongcare/notice/model/data/remote/NoticeRetrofitClient.kt
  app/src/main/java/com/project/meongcare/notice/model/data/repository/NoticeModule.kt
  app/src/main/java/com/project/meongcare/notice/model/data/repository/NoticeRepository.kt
  app/src/main/java/com/project/meongcare/notice/model/data/repository/NoticeRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/notice/model/entities/NoticeGetListResponse.kt
  app/src/main/java/com/project/meongcare/notice/view/EventAdapter.kt
  app/src/main/java/com/project/meongcare/notice/view/NoticeAdapter.kt
  app/src/main/java/com/project/meongcare/notice/view/NoticeFragment.kt
  app/src/main/java/com/project/meongcare/notice/view/NoticeTabEventFragment.kt
  app/src/main/java/com/project/meongcare/notice/view/NoticeTabNoticeFragment.kt
  app/src/main/java/com/project/meongcare/notice/viewmodel/NoticeViewModel.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditFragment.kt
  app/src/main/res/drawable/notice_no_list_icon.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_notice_tab_event.xml
  app/src/main/res/layout/fragment_notice_tab_notice.xml
  app/src/main/res/layout/item_notice_content.xml
  app/src/main/res/layout/item_notice_header.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat
