Repository Semoban/meongcare-AOS, pull requests merged in 2024-04, with the labels that each got.

#173 feat: 진료기록 정보 화면 관련 기능 구현 완료, 진료기록 생성 화면 null 체크까지 진행중
  app/src/main/java/com/project/meongcare/MedicalRecordAddFragment.kt
  app/src/main/java/com/project/meongcare/OnPictureChangedListener.kt
  app/src/main/java/com/project/meongcare/login/view/GlobalApplication.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/data/local/MedicalRecordItemCheckListener.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/data/local/MedicalRecordItemClickListener.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/data/local/OnPictureChangedListener.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/data/remote/MedicalRecordApi.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/data/repository/MedicalRecordModule.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/data/repository/MedicalRecordRepository.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/data/repository/MedicalRecordRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/entities/MedicalRecord.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/entities/MedicalRecordDto.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/entities/MedicalRecordGet.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/entities/MedicalRecordGetResponse.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/entities/RequestMedicalRecord.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/utils/MedicalRecordDateUtils.kt
  app/src/main/java/com/project/meongcare/medicalrecord/model/utils/MedicalRecordUtils.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/MedicalRecordAddFragment.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/MedicalRecordEditFragment.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/MedicalRecordEditListAdapter.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/MedicalRecordFragment.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/MedicalRecordInfoFragment.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/MedicalRecordListAdapter.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/bottomSheet/MedicalRecordDateBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/medicalrecord/view/bottomSheet/MedicalRecordPictureBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/medicalrecord/viewmodel/DogViewModel.kt
  app/src/main/java/com/project/meongcare/medicalrecord/viewmodel/MedicalRecordViewModel.kt
  app/src/main/java/com/project/meongcare/medicalrecord/viewmodel/UserViewModel.kt
  app/src/main/res/drawable/medical_record_add_carrier.xml
  app/src/main/res/layout/bottomsheet_medical_record_add_date.xml
  app/src/main/res/layout/bottomsheet_medical_record_add_picture.xml
  app/src/main/res/layout/fragment_medical_record_add.xml
  app/src/main/res/layout/fragment_medical_record_info.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings-medicalrecord.xml
  app/src/main/res/xml/file_paths.xml
Labels: feat, refactor, design

#177 docs: 리드미 작성
  README.md
Labels: docs

#178 fix: 진료기록 이미지 처리 로직 변경
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/medicalRecord/model/data/remote/MedicalRecordApi.kt
  app/src/main/java/com/project/meongcare/medicalRecord/model/data/repository/MedicalRecordRepository.kt
  app/src/main/java/com/project/meongcare/medicalRecord/model/data/repository/MedicalRecordRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/medicalRecord/model/entities/MedicalRecordDto.kt
  app/src/main/java/com/project/meongcare/medicalRecord/model/entities/MedicalRecordGet.kt
  app/src/main/java/com/project/meongcare/medicalRecord/model/entities/MedicalRecordPutDto.kt
  app/src/main/java/com/project/meongcare/medicalRecord/view/MedicalRecordAddFragment.kt
  app/src/main/java/com/project/meongcare/medicalRecord/view/MedicalRecordInfoEditFragment.kt
  app/src/main/java/com/project/meongcare/medicalRecord/viewmodel/MedicalRecordViewModel.kt
Labels: feat
