Repository Semoban/meongcare-AOS, pull requests merged in 2024-02, with the labels that each got.

#144 design: 체중 수정 다이얼로그 체중 입력란 글자 길이 6으로 제한
  app/src/main/res/layout/layout_weight_edit_dialog.xml
Labels: design

#151 refactor: Dialog 클래스로 체중 편집 기능 수정, 주차별 체중 그래프의 마커 비활성화
  app/src/main/java/com/project/meongcare/weight/view/WeightFragment.kt
  app/src/main/res/layout/layout_weight_edit_dialog.xml
  app/src/main/res/values/themes.xml
Labels: refactor

#152 feat: 사료 중단 여부 확인 다이얼로그 구현
  app/src/main/java/com/project/meongcare/feed/view/FeedFragment.kt
  app/src/main/res/layout/layout_feed_stop_dialog.xml
Labels: feat, design

#153 feat: 이상증상 테스터 리뷰 반영하여 로직 추가
  app/src/main/java/com/project/meongcare/symptom/view/SymptomAddFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomSelectFragment.kt
  app/src/main/res/drawable/all_rect_gray2_r5_outline_gray3.xml
  app/src/main/res/layout/fragment_symptom_add.xml
  app/src/main/res/layout/fragment_symptom_select.xml
  app/src/main/res/layout/item_symptom.xml
Labels: feat, refactor, design

#155 refactor: 알림 아이콘 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/meongcare/login/model/data/repository/FirebaseCloudMessagingService.kt
  app/src/main/res/drawable/semoban_notification_icon.PNG
  app/src/main/res/values/strings.xml
Labels: refactor

#156 refactor: 강아지 품종 직접 입력 추가, 생일 바텀시트 변경 및 디자인 수정사항 반영
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/meongcare/BirthdayBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/java/com/project/meongcare/home/view/LoadingDialog.kt
  app/src/main/java/com/project/meongcare/info/model/data/remote/ProfileApi.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/login/model/data/local/UserPreferences.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogAddOnBoardingFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogVarietySearchFragment.kt
  app/src/main/res/drawable/main_fab_unclicked.xml
  app/src/main/res/drawable/onboarding_one.xml
  app/src/main/res/drawable/onboarding_three.xml
  app/src/main/res/drawable/onboarding_two.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_birthday_bottom_sheet.xml
  app/src/main/res/layout/fragment_dog_add_on_boarding.xml
  app/src/main/res/layout/fragment_dog_variety_search.xml
  app/src/main/res/layout/fragment_first_on_boarding.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_on_boarding.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_second_on_boarding.xml
  app/src/main/res/layout/fragment_third_on_boarding.xml
  app/src/main/res/layout/layout_input_dog_type_dialog.xml
  app/src/main/res/layout/layout_logout_dialog.xml
  app/src/main/res/layout/layout_medical_record_dialog.xml
  app/src/main/res/layout/loading_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings-petadd.xml
  app/src/main/res/values/strings-snackbar.xml
  app/src/main/res/values/styles.xml
Labels: bug, refactor, design

#159 fix: 사료 PUT 시 이미지 수정하지 않았을 때 이미지가 사라지는 현상 해결
  app/src/main/java/com/project/meongcare/feed/model/utils/FeedInfoUtils.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedEditFragment.kt
Labels: bug

#161 fix: 강아지 정보 수정 시 이미지 미등록 버그 수정
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/info/view/PetEditFragment.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/info/view/SettingFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogVarietySearchFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/viewmodel/DogTypeViewModel.kt
  app/src/main/res/layout/fragment_birthday_bottom_sheet.xml
  app/src/main/res/layout/fragment_dog_variety_search.xml
  app/src/main/res/layout/fragment_pet_edit.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/layout_delete_account_dialog.xml
Labels: bug, feat, design

#162 fix: 서버 도메인 변경 및 통신 API 엔드포인트 수정
  app/build.gradle
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/remote/ExcretaClient.kt
  app/src/main/java/com/project/meongcare/feed/model/data/remote/FeedClient.kt
  app/src/main/java/com/project/meongcare/home/model/data/remote/HomeApi.kt
  app/src/main/java/com/project/meongcare/home/model/data/remote/HomeRetrofitClient.kt
  app/src/main/java/com/project/meongcare/info/model/data/remote/ProfileApi.kt
  app/src/main/java/com/project/meongcare/info/model/data/remote/ProfileRetrofitClient.kt
  app/src/main/java/com/project/meongcare/login/model/data/remote/LoginApi.kt
  app/src/main/java/com/project/meongcare/login/model/data/remote/LoginRetrofitClient.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/java/com/project/meongcare/notice/model/data/remote/NoticeApi.kt
  app/src/main/java/com/project/meongcare/notice/model/data/remote/NoticeRetrofitClient.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/remote/DogAddApi.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/remote/DogAddRetrofitClient.kt
  app/src/main/java/com/project/meongcare/supplement/model/data/remote/SupplementAPI.kt
  app/src/main/java/com/project/meongcare/symptom/model/data/remote/SymptomAPI.kt
  app/src/main/java/com/project/meongcare/weight/model/data/remote/WeightClient.kt
Labels: refactor, chore

#163 design: 구글 로그인 버튼 비활성화
  .github/workflows/main.yml
  app/build.gradle
  app/src/.editorconfig
  app/src/main/res/layout/fragment_login.xml
Labels: design

#165 fix: 홈 화면에서 통신 오류 발생 시 로딩 화면 종료되지 않는 현상 해결
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
Labels: bug
