Repository Semoban/meongcare-AOS, pull requests merged in 2024-01, with the labels that each got.

#79 feat: 대소변 POST, GET, PATCH, DELETE 기능 구현
  app/build.gradle
  app/src/main/java/com/project/meongcare/ExcretaAddFragment.kt
  app/src/main/java/com/project/meongcare/ExcretaFragment.kt
  app/src/main/java/com/project/meongcare/ExcretaInfoFragment.kt
  app/src/main/java/com/project/meongcare/ExcretaRecordEditFragment.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/local/ExcretaItemCheckedListener.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/local/PhotoListener.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/remote/ExcretaClient.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/remote/ExcretaRemoteDataSource.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/remote/ExcretaService.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/repository/ExcretaModule.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/repository/ExcretaRepository.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/repository/ExcretaRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/Excreta.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/ExcretaDetailGetResponse.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/ExcretaInfo.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/ExcretaInfoPatch.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/ExcretaRecord.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/ExcretaRecordGetRequest.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/ExcretaRecordGetResponse.kt
  app/src/main/java/com/project/meongcare/excreta/model/entities/ExcretaUploadRequest.kt
  app/src/main/java/com/project/meongcare/excreta/utils/ExcretaConstants.kt
  app/src/main/java/com/project/meongcare/excreta/utils/ExcretaDateTimeUtils.kt
  app/src/main/java/com/project/meongcare/excreta/utils/ExcretaInfoUtils.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaAdapter.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaAddFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaEditFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaInfoFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaRecordEditAdapter.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaRecordEditFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/PhotoAttachModalBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaAddViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaDeleteViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaDetailViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaPatchViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaRecordViewModel.kt
  app/src/main/res/drawable/excreta_feces.xml
  app/src/main/res/drawable/excreta_image_visibility_off.xml
  app/src/main/res/drawable/excreta_visibility_off.xml
  app/src/main/res/layout/fragment_excreta.xml
  app/src/main/res/layout/fragment_excreta_add.xml
  app/src/main/res/layout/fragment_excreta_add_edit.xml
  app/src/main/res/layout/fragment_excreta_info.xml
  app/src/main/res/layout/fragment_excreta_record_edit.xml
  app/src/main/res/layout/item_excreta_record.xml
  app/src/main/res/layout/item_excreta_record_edit.xml
  app/src/main/res/layout/layout_excreta_attach_photo.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/xml/file_paths.xml
Labels: feat

#86 feat: 홈 화면 강아지 체중 dataStore에 저장
  app/src/main/java/com/project/meongcare/home/model/data/local/DogPreferences.kt
  app/src/main/java/com/project/meongcare/home/model/data/local/DogProfileClickListener.kt
  app/src/main/java/com/project/meongcare/home/model/data/local/HorizonCalendarItemClickListener.kt
  app/src/main/java/com/project/meongcare/home/view/HomeDogProfileAdapter.kt
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/java/com/project/meongcare/home/view/HomeHorizonCalendarAdapter.kt
Labels: feat

#87 feat: 내정보, 강아지 정보 수정, 설정 화면 기능 구현
  app/src/main/java/com/project/meongcare/PetAddFragment.kt
  app/src/main/java/com/project/meongcare/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/SettingFragment.kt
  app/src/main/java/com/project/meongcare/home/model/data/remote/HomeApi.kt
  app/src/main/java/com/project/meongcare/home/model/data/repository/HomeRepository.kt
  app/src/main/java/com/project/meongcare/home/model/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/home/model/entities/GetDogListResponse.kt
  app/src/main/java/com/project/meongcare/home/model/entities/GetUserProfileResponse.kt
  app/src/main/java/com/project/meongcare/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/project/meongcare/info/model/data/remote/ProfileApi.kt
  app/src/main/java/com/project/meongcare/info/model/data/remote/ProfileRetrofitClient.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileModule.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepository.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/info/model/entities/GetDogInfoResponse.kt
  app/src/main/java/com/project/meongcare/info/view/PetEditFragment.kt
  app/src/main/java/com/project/meongcare/info/view/PetInfoFragment.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileDogAdapter.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/info/view/SettingFragment.kt
  app/src/main/java/com/project/meongcare/info/view/UserProfileSelectBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/info/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/project/meongcare/login/model/data/local/UserPreferences.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/local/PhotoMenuListener.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogAddOnBoardingFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogVarietySearchFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/PhotoSelectBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomInfoFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditFragment.kt
  app/src/main/res/drawable/all_snack_bar_complete.xml
  app/src/main/res/drawable/dog_profile_default.xml
  app/src/main/res/drawable/profile_default_image.xml
  app/src/main/res/drawable/profile_r11.xml
  app/src/main/res/layout/fragment_pet_add_edit.xml
  app/src/main/res/layout/fragment_pet_edit.xml
  app/src/main/res/layout/fragment_photo_select_bottom_sheet.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/fragment_symptom_info.xml
  app/src/main/res/layout/fragment_symptom_list_edit.xml
  app/src/main/res/layout/item_pet.xml
  app/src/main/res/layout/layout_delete_account_dialog.xml
  app/src/main/res/layout/layout_delete_dialog.xml
  app/src/main/res/layout/layout_logout_dialog.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings-petadd.xml
  app/src/main/res/xml/file_paths.xml
Labels: feat, design

#88 feat: 품종 검색 기능 구현
  app/src/main/assets/dog_types.json
  app/src/main/java/com/project/meongcare/info/view/PetEditFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/local/DogTypeSelectListener.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/repository/DogTypeModule.kt
  app/src/main/java/com/project/meongcare/onboarding/model/data/repository/DogTypeRepository.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogAddOnBoardingFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogTypeAdapter.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogVarietySearchFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/viewmodel/DogTypeSharedViewModel.kt
  app/src/main/java/com/project/meongcare/onboarding/viewmodel/DogTypeViewModel.kt
  app/src/main/res/drawable/dog_search_item_icon.xml
  app/src/main/res/layout/fragment_dog_variety_search.xml
  app/src/main/res/layout/fragment_pet_edit.xml
  app/src/main/res/layout/item_search_dog_variety.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat, design

#90 feat: 영양제 관련 기능 구현
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/project/meongcare/supplement/model/data/local/OnPictureChangedListener.kt
  app/src/main/java/com/project/meongcare/supplement/model/data/remote/RetrofitInstance.kt
  app/src/main/java/com/project/meongcare/supplement/model/data/remote/SupplementAPI.kt
  app/src/main/java/com/project/meongcare/supplement/model/data/repository/SupplementRepository.kt
  app/src/main/java/com/project/meongcare/supplement/model/entities/SupplementData.kt
  app/src/main/java/com/project/meongcare/supplement/utils/SupplementUtils.kt
  app/src/main/java/com/project/meongcare/supplement/view/SupplementAddFragment.kt
  app/src/main/java/com/project/meongcare/supplement/view/SupplementFragment.kt
  app/src/main/java/com/project/meongcare/supplement/view/SupplementInfoFragment.kt
  app/src/main/java/com/project/meongcare/supplement/view/SupplementRoutineEditFragment.kt
  app/src/main/java/com/project/meongcare/supplement/view/bottomSheet/SupplementCycleBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/supplement/view/bottomSheet/SupplementPictureBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/supplement/view/bottomSheet/SupplementTimeBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/supplement/viewmodel/SupplementViewModel.kt
  app/src/main/java/com/project/meongcare/supplement/viewmodel/SupplementViewModelFactory.kt
  app/src/main/java/com/project/meongcare/symptom/utils/SymptomUtils.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomAddFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomInfoFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/viewmodel/SymptomViewModel.kt
  app/src/main/java/com/project/meongcare/toolbar/view/ToolbarDateRecyclerViewAdapter.kt
  app/src/main/java/com/project/meongcare/toolbar/view/ToolbarFragment.kt
  app/src/main/java/com/project/meongcare/toolbar/viewmodel/ToolbarViewModel.kt
  app/src/main/res/drawable/all_check_toggle_20dp.xml
  app/src/main/res/drawable/all_notification_toggle_18dp.xml
  app/src/main/res/drawable/all_rect_gray2_r10_outline.xml
  app/src/main/res/drawable/all_rect_gray3_r5_outline.xml
  app/src/main/res/drawable/all_rect_main1_r5.xml
  app/src/main/res/drawable/all_rect_main1_r5_outline_main3.xml
  app/src/main/res/drawable/supplement_button_toggle.xml
  app/src/main/res/drawable/supplement_img_default.xml
  app/src/main/res/drawable/supplement_progress_bar.xml
  app/src/main/res/layout/bottomsheet_supplement_add_cycle.xml
  app/src/main/res/layout/bottomsheet_supplement_add_picture.xml
  app/src/main/res/layout/bottomsheet_supplement_add_time.xml
  app/src/main/res/layout/fragment_supplement.xml
  app/src/main/res/layout/fragment_supplement_add.xml
  app/src/main/res/layout/fragment_supplement_info.xml
  app/src/main/res/layout/fragment_supplement_routine_edit.xml
  app/src/main/res/layout/item_supplement.xml
  app/src/main/res/layout/item_supplement_add_time.xml
  app/src/main/res/layout/item_supplement_routine_edit.xml
  app/src/main/res/layout/layout_delete_dialog.xml
  app/src/main/res/menu/menu_delete.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/xml/file_paths.xml
Labels: feat, design

#91 프로필 이미지 PATCH, 알림 GET api 연결
  app/src/main/java/com/project/meongcare/home/model/entities/GetUserProfileResponse.kt
  app/src/main/java/com/project/meongcare/info/model/data/remote/ProfileApi.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepository.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/info/view/SettingFragment.kt
  app/src/main/java/com/project/meongcare/info/view/UserProfileSelectBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/info/viewmodel/ProfileViewModel.kt
  app/src/main/res/layout/fragment_photo_select_bottom_sheet.xml
Labels: feat, design

#99 feat: 사료 POST, PUT, PATCH, GET, DELETE 구현
  app/src/main/java/com/project/meongcare/FeedAddFragment.kt
  app/src/main/java/com/project/meongcare/FeedFragment.kt
  app/src/main/java/com/project/meongcare/FeedInfoFragment.kt
  app/src/main/java/com/project/meongcare/OldFeedFragment.kt
  app/src/main/java/com/project/meongcare/SearchFeedFragment.kt
  app/src/main/java/com/project/meongcare/feed/model/data/local/FeedItemSelectionListener.kt
  app/src/main/java/com/project/meongcare/feed/model/data/local/FeedPhotoListener.kt
  app/src/main/java/com/project/meongcare/feed/model/data/remote/FeedClient.kt
  app/src/main/java/com/project/meongcare/feed/model/data/remote/FeedRemoteDataSource.kt
  app/src/main/java/com/project/meongcare/feed/model/data/remote/FeedService.kt
  app/src/main/java/com/project/meongcare/feed/model/data/repository/FeedModule.kt
  app/src/main/java/com/project/meongcare/feed/model/data/repository/FeedRepository.kt
  app/src/main/java/com/project/meongcare/feed/model/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/Feed.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedDetailGetResponse.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedGetResponse.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedInfo.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedPartRecord.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedPartRecords.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedPatchRequest.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedPutInfo.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedRecord.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedRecords.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedUploadRequest.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/Feeds.kt
  app/src/main/java/com/project/meongcare/feed/model/utils/FeedDateUtils.kt
  app/src/main/java/com/project/meongcare/feed/model/utils/FeedInfoUtils.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedAddFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedEditFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedInfoFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedPartAdapter.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedPhotoAttachModalBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedsAdapter.kt
  app/src/main/java/com/project/meongcare/feed/view/OldFeedFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/PreviousFeedAdapter.kt
  app/src/main/java/com/project/meongcare/feed/view/SearchFeedFragment.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedDeleteViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedDetailGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPartGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPatchViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPostViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPutViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedsGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/PreviousFeedGetViewModel.kt
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_feed_add_edit.xml
  app/src/main/res/layout/fragment_feed_info.xml
  app/src/main/res/layout/fragment_old_feed.xml
  app/src/main/res/layout/fragment_search_feed.xml
  app/src/main/res/layout/layout_feed_attach_photo.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/xml/file_paths.xml
Labels: feat

#106 fix: 이상증상 관련 api 통신 에러 해결
  app/src/main/java/com/project/meongcare/snackbar/view/CustomSnackBar.kt
  app/src/main/java/com/project/meongcare/supplement/model/data/remote/SupplementRetrofitInstance.kt
  app/src/main/java/com/project/meongcare/supplement/model/data/repository/SupplementRepository.kt
  app/src/main/java/com/project/meongcare/symptom/model/data/remote/SymptomAPI.kt
  app/src/main/java/com/project/meongcare/symptom/model/data/remote/SymptomRetrofitInstance.kt
  app/src/main/java/com/project/meongcare/symptom/model/data/repository/SymptomRepository.kt
  app/src/main/java/com/project/meongcare/symptom/model/entities/SymptomData.kt
  app/src/main/java/com/project/meongcare/symptom/utils/SymptomUtils.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomAddFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomInfoFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditRecyclerViewAdapter.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomRecyclerViewAdapter.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomSelectFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/bottomSheet/SymptomBottomSheetDialogFragment.kt
  app/src/main/java/com/project/meongcare/symptom/viewmodel/SymptomViewModel.kt
  app/src/main/java/com/project/meongcare/symptom/viewmodel/SymptomViewModelFactory.kt
  app/src/main/java/com/project/meongcare/toolbar/view/ToolbarFragment.kt
  app/src/main/res/drawable/snackbar_error_16dp.xml
  app/src/main/res/drawable/snackbar_success_16dp.xml
  app/src/main/res/layout/fragment_symptom.xml
  app/src/main/res/layout/fragment_symptom_edit.xml
  app/src/main/res/layout/fragment_symptom_list_edit.xml
  app/src/main/res/layout/fragment_symptom_select.xml
  app/src/main/res/layout/item_symptom.xml
  app/src/main/res/layout/item_symptom_add.xml
  app/src/main/res/layout/item_symptom_list_edit.xml
  app/src/main/res/layout/layout_snackbar.xml
Labels: bug, refactor

#110 design: 앱 이름 변경에 따른 디자인 수정사항 적용
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/meongcare_logo_login.xml
  app/src/main/res/drawable/meongcare_logo_splash.xml
  app/src/main/res/drawable/semoban_logo.xml
  app/src/main/res/drawable/semoban_logo_splash.xml
  app/src/main/res/drawable/snackbar_complete_icon.xml
  app/src/main/res/drawable/snackbar_failure_icon.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_dog_add_on_boarding.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_third_on_boarding.xml
Labels: design

#111 feat: 화면 이동 로직 추가
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/info/view/SettingFragment.kt
  app/src/main/java/com/project/meongcare/login/model/data/local/UserPreferences.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: feat, design

#113 refactor: 사료 유효성 검사 로직 추가 및 임시 값 data store 값으로 교체
  app/src/main/java/com/project/meongcare/feed/model/data/remote/FeedRemoteDataSource.kt
  app/src/main/java/com/project/meongcare/feed/model/data/repository/FeedRepository.kt
  app/src/main/java/com/project/meongcare/feed/model/data/repository/FeedRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/feed/model/entities/FeedPutInfo.kt
  app/src/main/java/com/project/meongcare/feed/model/utils/FeedInfoUtils.kt
  app/src/main/java/com/project/meongcare/feed/model/utils/FeedValidationUtils.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedAddFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedEditFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedInfoFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/FeedPartAdapter.kt
  app/src/main/java/com/project/meongcare/feed/view/OldFeedFragment.kt
  app/src/main/java/com/project/meongcare/feed/view/PreviousFeedAdapter.kt
  app/src/main/java/com/project/meongcare/feed/view/SearchFeedFragment.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/DogViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedDeleteViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedDetailGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPartGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPatchViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPostViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedPutViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/FeedsGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/PreviousFeedGetViewModel.kt
  app/src/main/java/com/project/meongcare/feed/viewmodel/UserViewModel.kt
  app/src/main/res/drawable/all_rect_white_r5_outline_sub1.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_feed_add_edit.xml
  app/src/main/res/layout/fragment_feed_info.xml
  app/src/main/res/layout/layout_delete_dialog.xml
Labels: feat, refactor

#116 refactor: 체중 유효성 검사 로직 추가 및 임시 값 data store 값으로 교체
  app/src/main/java/com/project/meongcare/feed/viewmodel/DogViewModel.kt
  app/src/main/java/com/project/meongcare/weight/model/data/remote/WeightRemoteDataSource.kt
  app/src/main/java/com/project/meongcare/weight/model/data/repository/WeightRepository.kt
  app/src/main/java/com/project/meongcare/weight/model/data/repository/WeightRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/weight/view/WeightFragment.kt
  app/src/main/java/com/project/meongcare/weight/viewmodel/WeightViewModel.kt
  app/src/main/res/layout/fragment_weight.xml
  app/src/main/res/layout/layout_weight_edit_dialog.xml
Labels: feat, refactor

#120 feat: api 통신 중 access, refresh 토큰 만료 시 처리 로직 구현
  app/src/main/java/com/project/meongcare/home/model/data/repository/HomeRepository.kt
  app/src/main/java/com/project/meongcare/home/model/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/java/com/project/meongcare/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepository.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/info/view/PetEditFragment.kt
  app/src/main/java/com/project/meongcare/info/view/PetInfoFragment.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/info/view/SettingFragment.kt
  app/src/main/java/com/project/meongcare/info/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/project/meongcare/login/model/data/local/UserPreferences.kt
  app/src/main/java/com/project/meongcare/login/model/data/repository/LoginRepository.kt
  app/src/main/java/com/project/meongcare/login/model/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogAddOnBoardingFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings-snackbar.xml
Labels: docs, feat, design

#121 fix: 사용자 로그인 이력에 따라 화면 전환하는 로직 수정
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/java/com/project/meongcare/login/model/entities/LoginResponse.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/res/values/strings-snackbar.xml
Labels: docs, feat

#122 chore, design: 세로모드 지원 활성화, 앱 아이콘 이미지 추가
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/fragment_supplement_add.xml
  app/src/main/res/layout/fragment_supplement_info.xml
  app/src/main/res/layout/item_supplement_search.xml
  app/src/main/res/layout/item_symptom.xml
  app/src/main/res/layout/item_symptom_add.xml
  app/src/main/res/layout/item_symptom_list_edit.xml
  app/src/main/res/layout/item_symptom_select.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: design, chore

#125 fix: 캘린더 bottom sheet 및 bottom navigation 관련 버그 수정
  app/src/main/java/com/project/meongcare/CalendarBottomSheetFragment.kt
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/info/view/PetEditFragment.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogAddOnBoardingFragment.kt
  app/src/main/res/layout/fragment_calendar_bottom_sheet.xml
Labels: bug

#126 feat: 시스템 백버튼 관리 로직 추가
  app/src/main/java/com/project/meongcare/MainActivity.kt
Labels: feat

#127 design: scroll 되지 않는 현상 해결
  app/src/main/res/layout/fragment_home.xml
Labels: design

#128 fix: 구글 로그인 식별자 오류 및 뷰모델 갱신 오류 해결
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/java/com/project/meongcare/info/view/PetInfoFragment.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
Labels: bug

#130 feat: 강아지 이름 연결 및 이상증상 전체선택 로직 수정
  app/src/main/java/com/project/meongcare/supplement/view/SupplementFragment.kt
  app/src/main/java/com/project/meongcare/supplement/viewmodel/SupplementViewModel.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomInfoFragment.kt
  app/src/main/java/com/project/meongcare/symptom/view/SymptomListEditFragment.kt
  app/src/main/java/com/project/meongcare/symptom/viewmodel/SymptomViewModel.kt
Labels: feat

#133 design: 스크롤 안되는 현상 해결
  app/src/main/res/layout/fragment_symptom_select.xml
Labels: bug, design

#134 design: 섭취량 글씨 잘리는 현상 해결
  app/src/main/res/layout/bottomsheet_supplement_add_time.xml
Labels: bug, design

#132 refactor: 대소변 유효성 검사 로직 추가 및 임시 값 data store 값으로 교체
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/remote/ExcretaRemoteDataSource.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/repository/ExcretaRepository.kt
  app/src/main/java/com/project/meongcare/excreta/model/data/repository/ExcretaRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/excreta/utils/ExcretaConstants.kt
  app/src/main/java/com/project/meongcare/excreta/utils/ExcretaDateTimeUtils.kt
  app/src/main/java/com/project/meongcare/excreta/utils/ExcretaInfoUtils.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaAdapter.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaAddFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaEditFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaInfoFragment.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaRecordEditAdapter.kt
  app/src/main/java/com/project/meongcare/excreta/view/ExcretaRecordEditFragment.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaAddViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaDeleteViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaDetailViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaPatchViewModel.kt
  app/src/main/java/com/project/meongcare/excreta/viewmodel/ExcretaRecordViewModel.kt
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/res/layout/fragment_excreta.xml
  app/src/main/res/layout/fragment_excreta_add_edit.xml
  app/src/main/res/layout/item_excreta_record.xml
  app/src/main/res/values/typography.xml
Labels: feat, refactor

#136 refactor: 응답 처리 및 디자인 수정, 알림 채널 등록
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/project/meongcare/MainActivity.kt
  app/src/main/java/com/project/meongcare/home/view/HomeFragment.kt
  app/src/main/java/com/project/meongcare/info/model/data/remote/ProfileApi.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepository.kt
  app/src/main/java/com/project/meongcare/info/model/data/repository/ProfileRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/info/view/PetEditFragment.kt
  app/src/main/java/com/project/meongcare/info/view/ProfileFragment.kt
  app/src/main/java/com/project/meongcare/info/view/SettingFragment.kt
  app/src/main/java/com/project/meongcare/info/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/project/meongcare/login/model/data/repository/FirebaseCloudMessagingService.kt
  app/src/main/java/com/project/meongcare/login/model/data/repository/LoginRepository.kt
  app/src/main/java/com/project/meongcare/login/model/data/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/project/meongcare/login/model/entities/LoginRequest.kt
  app/src/main/java/com/project/meongcare/login/view/LoginFragment.kt
  app/src/main/java/com/project/meongcare/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/project/meongcare/onboarding/view/DogVarietySearchFragment.kt
  app/src/main/res/drawable/semoban_icon.PNG
  app/src/main/res/layout/fragment_dog_add_on_boarding.xml
  app/src/main/res/layout/fragment_first_on_boarding.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_pet_edit.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_second_on_boarding.xml
  app/src/main/res/layout/fragment_third_on_boarding.xml
  app/src/main/res/values/strings-snackbar.xml
Labels: docs, feat, refactor, design, chore
